environment:
  nodejs_version: "0.12"

clone_folder: c:\projects\defaultencodingproof

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

after_test:
  - 7z a -r dist.zip dist
  - ps: Push-AppveyorArtifact dist.zip -DeploymentName distDir
